
insert into CURRENCY_EXCHANGE (ID, CONVERSION_MULTIPLE, CURRENCY_FROM, CURRENCY_TO) values (1, 80.50, 'USD', 'BDT');
insert into CURRENCY_EXCHANGE (ID, CONVERSION_MULTIPLE, CURRENCY_FROM, CURRENCY_TO) values (2, 120.75, 'EURO', 'BDT');
insert into CURRENCY_EXCHANGE (ID, CONVERSION_MULTIPLE, CURRENCY_FROM, CURRENCY_TO) values (3, 75.45, 'AUD', 'BDT');
insert into CURRENCY_EXCHANGE (ID, CONVERSION_MULTIPLE, CURRENCY_FROM, CURRENCY_TO) values (4, 85.76, 'CAD', 'BDT');